//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nasrisite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sheet1_
    {
        public int UserReviewId { get; set; }
        public string UserReviewName { get; set; }
        public System.DateTime UserReviewDate { get; set; }
        public int UserReviewRating { get; set; }
        public string UserReviewDescription { get; set; }
        public int UserReviewAppCategory { get; set; }
        public bool UserReviewUse { get; set; }
        public bool UserReviewAnswerd { get; set; }
    }
}
